### ISSUE TITLE
Feature request - output folder select

### ISSUE THREAD

**Issue by Ravoit** [higoka/habbo-downloader#13]
Please make option to select desired output folder, so I can just update my existing files instead moveng them all every time

**Comment by higoka** [comment]
It downloads the files to the folder your currently in. You can `cd` into your desired output folder and run habbo-downloader normally. But i add a option for that too.

**Comment by higoka** [comment]
Implemented in v2.23.0.
There is a new option added to define the output folder: `--output /some/path` or shorthand `-o /some/path`

To update to latest version simply run: `npm i -g habbo-downloader`
