### ISSUE TITLE
Bug report - badge downloader don't work with numberic achievements

### ISSUE THREAD

**Issue by Ravoit** [higoka/habbo-downloader#14]
For example

badge_name_ACH_MusicCollector=Music Collector Level %roman%
is
https://images.habbo.com/c_images/album1584/ACH_MusicCollector1.png
...
https://images.habbo.com/c_images/album1584/ACH_MusicCollector20.png

**Comment by higoka** [comment]
Hm i didnt know that there are numeric badges. But i will need to see how inimplement that.

Thanks for the info.

**Comment by Ravoit** [comment]
I guess checking for "%roman%" in value and then just looping until 404 should work fine

**Comment by higoka** [comment]
Are these only on _ACH_ badges?

**Comment by Ravoit** [comment]
badge_name_ACH_MusicCollector=Music Collector Level %roman%
Is defined in texts :)

**Comment by higoka** [comment]
Yes but not the numbers
