### ISSUE TITLE
Remove Unity Files Downloader

### ISSUE THREAD

**Issue by higoka** [higoka/habbo-downloader#16]
I'm thinking of removing the unity files downloader script. You can't really do anything with the unity files and i doubt anyone uses it so i guess there is no point in keeping this.

Let me know what you think about that or if i should keep it.

**Comment by emansom** [comment]
Keep it for historical reasons, and back it up. A few times. Possibly off-site too. Twice. Twice off-site.

**Comment by Pi-Bouf** [comment]
Keep it Bro, one day it will be useful !
