### ISSUE TITLE
images furnis

### ISSUE THREAD

**Issue by habbboprogrammer25** [higoka/habbo-downloader#21]
Hello, would you know how to obtain the images of the furni

https://i.imgur.com/fN76AO2.png

I have seen that habbo fansites get them automatically?

**Comment by higoka** [comment]
These Images cant be downloaded from Habbo. You would need to render the sprites from the furniture .swf file. Maybe take a look at nitro renderer

**Comment by habbboprogrammer25** [comment]
> These Images cant be downloaded from Habbo. You would need to render the sprites from the furniture .swf file. Maybe take a look at nitro renderer
And with what program do you recommend to render the sprite?

**Comment by higoka** [comment]
There is no program you need to create one
