### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by victorlbs** [higoka/habbo-downloader#4]
how can i solve this? I'm running right?

C:\Users\Victor>cd c:\xampp\php

c:\xampp\php>php -f C:\xampp\htdocs\run
PHP Fatal error:  Default value for parameters with a class type hint can only b
e NULL in C:\xampp\htdocs\src\functions.php on line 3

Fatal error: Default value for parameters with a class type hint can only be NUL
L in C:\xampp\htdocs\src\functions.php on line 3

**Comment by victorlbs** [comment]
ok, i found out that my php is in the old library, i tested it in php 7.2, the result:

#! / usr / bin / php __ __ __ / / ___ _ / / / / ___ / _ \ / _ `/ _ \ / _ \ / _ \ /_//_/\_,_/_.__/ _.__ / \ ___ / __ ___ / / __ _ _____ / / __ ___ ____ / / __ ____ / _ / _ \ | / | / / _ \ / / _ \ / _ `/ _ / -_) __ / \ _, _ / \ ___ / __, __ / _ // _ / _ / \ ___ / \ _, _ / \ _, _ / \ __ / _ / initializing ... parsing current production ... error parsing production

**Comment by higoka** [comment]
okay, enable the error reporting.

change these lines: https://github.com/higoka/habbo-downloader/blob/master/run#L10-L15
to this:
```php
error_reporting(E_ALL);

ini_set('display_errors', true);
ini_set('display_startup_errors', true);
```

then run the downloader again, you now should see some errors, post it here.

**Comment by victorlbs** [comment]
I went to check the code and the error log is already activated 

http://prntscr.com/p2bag3

**Comment by higoka** [comment]
its not activated yet.

change `error_reporting(0);` to `error_reporting(E_ALL);`
and change `false` to `true` on both `ini_set()`

**Comment by victorlbs** [comment]
I think I already know the error, I am using vps and is blocking my access, I will download it on my computer and warn you, then I will test on cpanel

http://prntscr.com/p2bfeq 

(changed false to true now)

**Comment by higoka** [comment]
okay. let me know if it works or not.

**Comment by victorlbs** [comment]
http://prntscr.com/p2bo0f

ok it worked perfectly thank you so much for your support

**Comment by higoka** [comment]
you cant run it using your browser. you need to run it using the terminal

**Comment by victorlbs** [comment]
yes, it was just a test, I prefer to use in the browser, I will adapt the code to use via form with $ _POST if you allow
one question, can you tell me if this cron is correct?

> php -q / home / habbosho / public_html / run

**Comment by higoka** [comment]
sure you can modify what you want 👍 

about your question: 
i would use like this: `php -f /path/to/run`

**Comment by victorlbs** [comment]
ok congratulations on your work you are awesome
