### ISSUE TITLE
feature request

### ISSUE THREAD

**Issue by higoka** [higoka/habbo-downloader#5]
post your idea or feature request here. it does not have to be for this project only, i also down for creating completly new projects.

**planned**
- improve performance using parallel downloads
- display an error when a download failed @victorlbs

i try my best to implement as much as possible.

**Comment by victorlbs** [comment]
request: show error on console (badges and furnitures don't return any errors (don't download)) the others are all ok :) http://prntscr.com/p2fh9d

**Comment by higoka** [comment]
@victorlbs you saying that badges and furnitures dont get downloaded?

**Comment by victorlbs** [comment]
yes, but with a retro habbo worked the furniture, with the original habbo no

**Comment by higoka** [comment]
it works with retros if they dont have the cloudflare challenge enabled.

**Comment by victorlbs** [comment]
request: I don't know if it's possible with php, but it could have a function that extracts the big image from .swf

https://www.habbo.lc/furniload/furni/bonusbag19_3.png

**Comment by higoka** [comment]
this can easily be done with php.

good idea i add it to the list. i dont implement it into the downloader i rather create a seperate repository for the image extractor

**Comment by victorlbs** [comment]
I understand, I made the request because in the tool I'm building I'm using the small and large icons are much better

**Comment by higoka** [comment]
oh you need the large icons hmm. i already tried to do this years ago but there are some problems with the blendmodes.
https://picr.ws/i/6WT
[https://picr.ws/i/Rj3

i havent found any solution yet so i dont know if i can add the large icons but small icons should work

**Comment by victorlbs** [comment]
I will use the little ones for a while later I open the .swf one by one and save the image

http://prntscr.com/p64gao

**Comment by Menkz** [comment]
Would be cool to download images such as;
https://images.habbo.com/c_images/web_promo_small/
https://images.habbo.com/c_images/web_promo/
https://images.habbo.com/c_images/targetedoffers/

everything in https://habboo-a.akamaihd.net/c_images/catalogue/
(there's catalog headers - http://images-eussl.habbo.com/c_images/catalogue/val15_cata_header.gif)
