### ISSUE TITLE
PRODUCTION 2020?

### ISSUE THREAD

**Issue by tiuram0n** [higoka/habbo-downloader#8]
Have a PRODUCTION 2020?

**Comment by higoka** [comment]
You can download the latest PRODUCTION from Habbo.

**Comment by tiuram0n** [comment]
Would you have any programs or scripts to generate a "catalog_items" in the database format?

**Comment by higoka** [comment]
the closest i have is this: https://github.com/higoka/sql-creator-layout
its not really possible to automate this since the items have different width, length, price etc. so you would need to insert them manually.

**Comment by tiuram0n** [comment]
Could you provide me with an updated 2020 swf and emulator link?

**Comment by higoka** [comment]
check out arcturus morningstar: https://git.krews.org/morningstar/Arcturus-Community
this are the official swfs: https://git.krews.org/morningstar/morningstar-catalogue

**Comment by tiuram0n** [comment]
Sorry to bother. Could you provide me with a compatible database?

**Comment by higoka** [comment]
the database is included in the emu

**Comment by higoka** [comment]
Im going to close this issue since its not related to habbo-downloader.
